logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
spring:
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest

#configurations for cloudampq; cloud version of rabbit mq
#spring:
#  rabbitmq:
#    addresses: gull.rmq.cloudamqp.com
#    username: kiofdmer
#    password: GYTW8z7M-T_oO_-Me4-N3f1PX6bTVbTi
#    virtual-host: kiofdmer